version: '3.8'

services:
  mongo_db:
    image: mongo:7
    container_name: mongo_db
    environment:
      MONGO_INITDB_DATABASE: healthverify
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - healthcare_net

  server:
    build: ./server
    container_name: express_server
    environment:
      MONGODB_URI: "mongodb://mongo_db:27017/healthverify"
      PORT: 4000
      NODE_ENV: production
      JWT_SECRET: "healthcare_jwt_access_secret_key_2026_xyz"
      JWT_REFRESH_SECRET: "healthcare_jwt_refresh_secret_key_2026_xyz"
      CLIENT_URL: "http://localhost"
      SERVER_URL: "http://localhost:4000"
      VERIFICATION_SECRET: "supersecretmedicalverificationkey2026"
    ports:
      - "4000:4000"
    volumes:
      - upload_data:/usr/src/app/uploads
      - log_data:/usr/src/app/logs
    depends_on:
      mongo_db:
        condition: service_healthy
    networks:
      - healthcare_net

  client:
    build: ./client
    container_name: react_client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - healthcare_net

volumes:
  mongo_data:
  upload_data:
  log_data:

networks:
  healthcare_net:
    driver: bridge
